import React from "react";
import UserLogin from "@/components/modules/login";
import BasicLayout from "@/components/ui/layout/basicLayout";
import Head from "next/head";

const Login = () => (
  <>
    <Head>
      <title>Login - Home Assistance</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <UserLogin />
  </>
);

Login.getLayout = (page) => <BasicLayout>{page}</BasicLayout>;

export default Login;
